### ISSUE TITLE
3rd of <input> element overflow in <form> element

### ISSUE THREAD

**Issue by eminaltan** [eminaltan/band-template#8]
3rd <input> element of <Footer/> component overflow in <form> element. This problem should be fix.

**PLUS**

<input> elements not aligned well. 

Problems showed below code blocks.

***_footer.scss***

```scss
    form {
      margin-top: 40px;
      text-align: right;

      input {
        @extend .lato_15px;
        padding: 12px 8px;

        &:nth-child(2) {
          margin-left: 15px;
        }

        /** This element not overflow on parent element */
        &:nth-child(3) {
          display: block;
          width: 100%;
          margin-top: 10px;
        }
      }
    }
  }
```
